// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projexor.Data.Context;

#nullable disable

namespace Projexor.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250528010320_InitialDeploy")]
    partial class InitialDeploy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Projexor.Domain.Entity.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatAt")
                        .HasColumnType("SmallDateTime")
                        .HasColumnName("CreatAt");

                    b.HasKey("Id");

                    b.ToTable("UserAccount", (string)null);
                });

            modelBuilder.Entity("Projexor.Domain.Entity.UserAccount", b =>
                {
                    b.OwnsOne("Projexor.Domain.ValueObjects.Active", "Active", b1 =>
                        {
                            b1.Property<int>("UserAccountId")
                                .HasColumnType("Int");

                            b1.Property<bool>("Value")
                                .HasColumnType("Bit")
                                .HasColumnName("Active");

                            b1.HasKey("UserAccountId");

                            b1.ToTable("UserAccount");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.OwnsOne("Projexor.Domain.ValueObjects.BirthDate", "BirthDate", b1 =>
                        {
                            b1.Property<int>("UserAccountId")
                                .HasColumnType("Int");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("SmallDateTime")
                                .HasColumnName("BirthDate");

                            b1.HasKey("UserAccountId");

                            b1.ToTable("UserAccount");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.OwnsOne("Projexor.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<int>("UserAccountId")
                                .HasColumnType("Int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("Nvarchar(254)")
                                .HasColumnName("Email");

                            b1.HasKey("UserAccountId");

                            b1.HasIndex(new[] { "Value" }, "Unique_Key_Email_UserAccount")
                                .IsUnique();

                            b1.ToTable("UserAccount");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.OwnsOne("Projexor.Domain.ValueObjects.Login", "Login", b1 =>
                        {
                            b1.Property<int>("UserAccountId")
                                .HasColumnType("Int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("Nvarchar(30)")
                                .HasColumnName("Login");

                            b1.HasKey("UserAccountId");

                            b1.HasIndex(new[] { "Value" }, "Unique_Key_Login_UserAccount")
                                .IsUnique();

                            b1.ToTable("UserAccount");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.OwnsOne("Projexor.Domain.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<int>("UserAccountId")
                                .HasColumnType("Int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("Nvarchar(100)")
                                .HasColumnName("Name");

                            b1.HasKey("UserAccountId");

                            b1.ToTable("UserAccount");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.OwnsOne("Projexor.Domain.ValueObjects.Password", "PasswordHash", b1 =>
                        {
                            b1.Property<int>("UserAccountId")
                                .HasColumnType("Int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("NVarchar(64)")
                                .HasColumnName("PasswordHash");

                            b1.HasKey("UserAccountId");

                            b1.ToTable("UserAccount");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.OwnsOne("Projexor.Domain.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<int>("UserAccountId")
                                .HasColumnType("Int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("Nvarchar(20)")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("UserAccountId");

                            b1.HasIndex(new[] { "Value" }, "Unique_Key_PhoneNumber_UserAccount")
                                .IsUnique();

                            b1.ToTable("UserAccount");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.Navigation("Active")
                        .IsRequired();

                    b.Navigation("BirthDate")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Login")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("PasswordHash")
                        .IsRequired();

                    b.Navigation("PhoneNumber")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
